### ISSUE TITLE
Possible bug after restart of RMES

### ISSUE THREAD

**Issue by OpticOverlord** [Evolutionary-Intelligence/pypop#110]
Hi there,

I think there may be a bug in the handling of the delay factor in RMES.py after a restart - but I could be mistaken. After achieving convergence of an optimisation run, the implementation restarted the run;
``` 
 ....... *** restart *** .......
``` 

Then after one generation, resulted in an error. See following code output after restart 1;

``` 
* Generation 1: best_so_far_y -8.09000e-01, min(y) 2.19336e+01 & Evaluations 9352
Traceback (most recent call last):
  File "code.py", line 878, in <module>
    results = lmmaes.optimize()
  File "Python\Python39\lib\site-packages\pypop7\optimizers\es\rmes.py", line 154, in optimize       
    mean, p, s, mp, t_hat = self._update_distribution(x, mean, p, s, mp, t_hat, y, y_bak)
  File "Python\Python39\lib\site-packages\pypop7\optimizers\es\rmes.py", line 124, in _update_distribution
    mean, p, s = R1ES._update_distribution(self, x, mean, p, s, y, y_bak)
  File "Python\Python39\lib\site-packages\pypop7\optimizers\es\r1es.py", line 144, in _update_distribution
    self.sigma *= np.exp(s/self.d_sigma)
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

The inputs were as follows;

```options = {'fitness_threshold': -1000000,  
  'max_runtime': (17*60*60),  
  'seed_rng': 16, 
  'x': x,  
  'sigma': 1, 
  'verbose': 1,
  'saving_fitness': 100,
  'd_sigma': 10}
```

The problem had 100 dimensions. Any help would be greatly appreciated!

**Comment by Evolutionary-Intelligence** [comment]
Thanks for your attention. Could you provide a demo code (run-able) to repeat this result, in order to help us solve this issue? We find "lmmaes" vs "rmes" in your code output, however we do not meet this situation up to now. Thanks very much for your contributions.
